[project]
name = "mini-aes"
version = "0.1.0"
description = "Mini-AES Implementation with Streamlit UI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.32.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
